language: go

go: master

sudo: false

addons:
  apt:
    sources:
    - sourceline: 'ppa:masterminds/glide'
    packages:
    - glide

install: make dependencies

deploy:
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file: gcg
    skip_cleanup: true
    file_glob: true
    on:
      tags: true